import './tasks/build';
import './tasks/clean';
import './tasks/test';
import './tasks/serve';
import './tasks/properties';
import './tasks/posts';
import './tasks/cname';
import './tasks/sitemap';
import './tasks/pwa';
