/* Created by Aquariuslt on 22/04/2017.*/
export const REGISTER_NAV_MENUS = 'REGISTER_NAV_MENUS';
export const REGISTER_SUB_NAV_MENUS = 'REGISTER_SUB_NAV_MENUS';
export const LOAD_APPLICATION_PROPERTIES = 'LOAD_APPLICATION_PROPERTIES';
