export const LOAD_POSTS_INDEXES = 'LOAD_POSTS_INDEXES';

export const LOAD_POST_CONTENT = 'LOAD_POST_CONTENT';

export const REGISTER_CATEGORIES_MENU = 'REGISTER_CATEGORIES_MENU';
export const REGISTER_TAGS_MENU = 'REGISTER_TAGS_MENU';


export const UPDATE_POSTS_FILTER = 'UPDATE_POSTS_FILTER';
